########
#
#	Tree-Sitter Base and Common Language Parsers
#

CFLAGS ?= -O3

# OS-specific bits
ifneq ($(findstring darwin,$(shell $(CC) -dumpmachine)),)
	SOEXT = dylib
	LINKSHARED += -dynamiclib
else
	SOEXT = so
	LINKSHARED += -shared
endif

all: libtree-sitter.$(SOEXT) libtree-sitter-json.$(SOEXT)

libtree-sitter.$(SOEXT):
	@$(MAKE) -C tree-sitter libtree-sitter.$(SOEXT)
	@cp tree-sitter/libtree-sitter.$(SOEXT) .

########
#
#   C++
#
libtree-sitter-json.$(SOEXT):
	@$(MAKE) -C tree-sitter-json libtree-sitter-json.$(SOEXT)
	@cp tree-sitter-json/libtree-sitter-json.$(SOEXT) .

########
#
#	Clean
#
clean:
	@$(MAKE) -C tree-sitter clean
	@$(MAKE) -C tree-sitter-json clean
	-rm *.$(SOEXT) 2>/dev/null

.PHONY: all libtree-sitter.$(SOEXT) clean

# End of File.
